export { getPool, getSupabase } from "./client";
export * from "./auth-queries";
export * from "./otp-queries";
export * from "./capture-queries";
export * from "./streak-queries";
export * from "./leaderboard-queries";
export * from "./admin-queries";
export * from "./settings-queries";
export * from "./referral-queries";
export * from "./profile-queries";
export * from "./notification-queries";
export * from "./contact-queries";
export { ensureIndexes } from "./indexes";
